package com.hydraScrimTool.model;

import java.util.ArrayList;
import java.util.List;

import com.hydraScrimTool.model.planetside.Outfit;
import com.hydraScrimTool.model.planetside.Player;

/**
 * Class to store the event generated by the sockets.
 * @author david
 *
 */
public class EventStore {

	private List<Event> events;
	
	public EventStore() {
		this.events = new ArrayList<Event>();
	}
	
	/**
	 * Method to parse the event received from the socket
	 * @param jsonString
	 */
	public void addEvent(String jsonString) {
		
	}
	
	public List<Event> getEvents(){
		return events;
	}
	
	/**
	 * Get all events pertaining to a certain player
	 * @param player
	 * @return
	 */
	public List<Event> getEventsForPlayer(Player player){
		return events;
	}
	
	
	
	
}
